### ISSUE TITLE
Attention

### ISSUE THREAD

**Issue by damdafayton** [cynthiainga/ruby-group-capstone#49]
https://github.com/cynthiainga/ruby-group-capstone/blob/628c2ead47f4113ba1db3f46d54c111373c8108b/classes/item.rb#L15

@mwafrika @cynthiainga 
I guess the function was intended to do `genre.items.push()`? 

and similar for `author()` and `label()`

**Comment by cynthiainga** [comment]
Hello @damdafayton, you are right at this point and the function does that, it  push the given element at the end of the given array, I work on it to preserve data and load data maintained when we run the app
